sonar.projectKey=AparnaMounikau763_Ghcr-task
sonar.organization=aparnamounikau763

sonar.projectName=ghcr-task

sonar.sources=.
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=tests/*