sonar.projectKey=YOUR_PROJECT_KEY
sonar.organization=YOUR_ORGANIZATION

sonar.projectName=python-flask-ghcr

sonar.sources=.
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=tests/*